# NumPy Foundations

## 1. Why do arrays exist?

In [1]:
import numpy as np

ages = np.array([19, 21, 20, 22, 18])

print(ages)
print(type(ages))


[19 21 20 22 18]
<class 'numpy.ndarray'>


In [2]:
print(ages + 1)
print(ages * 2)
print(ages - 5)
print(ages / 2)

[20 22 21 23 19]
[38 42 40 44 36]
[14 16 15 17 13]
[ 9.5 10.5 10.  11.   9. ]


Normal Python List 

In [3]:
ages_list = [19, 21, 20, 22, 18]

print(ages_list + [1])
print(ages_list * 2)

[19, 21, 20, 22, 18, 1]
[19, 21, 20, 22, 18, 19, 21, 20, 22, 18]


In [8]:
ages + 1


array([20, 22, 21, 23, 19])

In [5]:
ages + np.array([1, 1, 1, 1, 1])

array([20, 22, 21, 23, 19])

In [7]:
ages + np.array([1, 2, 3, 4, 5])

array([20, 23, 23, 26, 23])

What I understand now: NumPy arrays allow numerical operations to be applied element-by-element, unlike Python lists where + means concatenation.

In [9]:
print(ages.ndim)
print(ages.shape)

1
(5,)


In [11]:
marks = np.array([
    [80, 75, 90],
    [65, 88, 72],
    [92, 81, 95]
])
print(marks)
print(marks.ndim)
print(marks.shape)

[[80 75 90]
 [65 88 72]
 [92 81 95]]
2
(3, 3)


In [12]:
print(marks[0])
print(marks[1])
print(marks[2])

[80 75 90]
[65 88 72]
[92 81 95]


In [13]:
print(marks[0, 0])
print(marks[1, 2])
print(marks[2, 1])

80
72
81


In [14]:
marks[:, 0]

array([80, 65, 92])

In [15]:
marks[0, :]

array([80, 75, 90])

In [16]:

marks[:2, :]

array([[80, 75, 90],
       [65, 88, 72]])

In [17]:
marks[:, :2]

array([[80, 75],
       [65, 88],
       [92, 81]])

In [18]:
marks + 5

array([[ 85,  80,  95],
       [ 70,  93,  77],
       [ 97,  86, 100]])

In [19]:
marks * 2

array([[160, 150, 180],
       [130, 176, 144],
       [184, 162, 190]])

In [20]:
marks[:, 0] + 10

array([ 90,  75, 102])

In [21]:
print(marks)

[[80 75 90]
 [65 88 72]
 [92 81 95]]


In [22]:
marks_list = [
    [80, 75, 90],
    [65, 88, 72],
    [92, 81, 95]
]

# Normal Python approach
result = []

for row in marks_list:
    new_row = []
    for mark in row:
        new_row.append(mark + 5)
    result.append(new_row)

print(result)

[[85, 80, 95], [70, 93, 77], [97, 86, 100]]


In [23]:
print(marks + 5)

[[ 85  80  95]
 [ 70  93  77]
 [ 97  86 100]]


In [24]:
big_array = np.arange(1_000_000)

In [25]:
big_array + 10

array([     10,      11,      12, ..., 1000007, 1000008, 1000009],
      shape=(1000000,))

In [26]:
marks.shape


(3, 3)

In [27]:
students = np.array([
    [80, 75, 90, 88],
    [65, 88, 72, 91],
    [92, 81, 95, 87]
])

print(students)
print(students.ndim)
print(students.shape)

[[80 75 90 88]
 [65 88 72 91]
 [92 81 95 87]]
2
(3, 4)


In [28]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

In [29]:
print(a + b)
print(a * b)

[11 22 33 44]
[ 10  40  90 160]


In [30]:
a = np.array([10, 20, 30, 40])
b = np.array([1])

print(a + b)

[11 21 31 41]


In [31]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3])

print(a + b)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [33]:
marks = np.array([
    [80, 75, 90],
    [65, 88, 72],
    [92, 81, 95]
])
print(marks.shape)

(3, 3)


In [34]:
marks_plus_5 = marks + 5

print(marks_plus_5)

[[ 85  80  95]
 [ 70  93  77]
 [ 97  86 100]]


In [35]:
bonus = np.array([5, 10, 0])

print(marks + bonus)

[[85 85 90]
 [70 98 72]
 [97 91 95]]


In [36]:
wrong_bonus = np.array([5, 10])

print(marks + wrong_bonus)

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [40]:
marks = np.array([
    [80, 75, 90],
    [65, 88, 72],
    [92, 81, 95]
])
print(marks.sum())

738


In [41]:
print(marks.sum(axis=1))

[245 225 268]


In [42]:
marks.sum(axis=0)

array([237, 244, 257])

In [43]:
print(marks.mean(axis=0))
print(marks.mean(axis=1))

[79.         81.33333333 85.66666667]
[81.66666667 75.         89.33333333]


In [44]:
print(marks.min())
print(marks.max())
print(marks.std())

65
95
9.498537899183338


In [45]:
print(marks.mean(axis=0))
print(marks.min(axis=0))
print(marks.max(axis=0))

[79.         81.33333333 85.66666667]
[65 75 72]
[92 88 95]


In [46]:
print(marks.mean(axis=1))
print(marks.min(axis=1))
print(marks.max(axis=1))

[81.66666667 75.         89.33333333]
[75 65 81]
[90 88 95]


In [47]:
X = np.array([
    [20, 500],
    [25, 700],
    [30, 900],
    [35, 1100]
])
print(X.mean(axis=0))

[ 27.5 800. ]


In [48]:
X.mean(axis=1)

array([260. , 362.5, 465. , 567.5])

In [49]:
import numpy as np

a = np.array([10, 20, 30, 40, 50, 60])

print(a.shape)

b = a.reshape(2, 3)

print(b)
print(b.shape)

(6,)
[[10 20 30]
 [40 50 60]]
(2, 3)


In [50]:
a.reshape(4, 2)

ValueError: cannot reshape array of size 6 into shape (4,2)

In [51]:
c = a.reshape(3, 2)

print(c)
print(c.shape)

[[10 20]
 [30 40]
 [50 60]]
(3, 2)


In [52]:
a.reshape(2, 3)

array([[10, 20, 30],
       [40, 50, 60]])

In [53]:
a.reshape(2, -1)

array([[10, 20, 30],
       [40, 50, 60]])

In [54]:
marks = np.array([45, 78, 92, 34, 67, 88])
marks > 60

array([False,  True,  True, False,  True,  True])

In [55]:
marks[marks > 60]

array([78, 92, 67, 88])

In [56]:
X = np.array([
    [20, 500],
    [25, 700],
    [30, 900],
    [35, 1100]
])

print(X[X[:, 0] > 25])

[[  30  900]
 [  35 1100]]


In [57]:
import numpy as np

X = np.array([
[20, 500],
[25, 700],
[30, 900],
[35, 1100],
[40, 1300]
])

print("Shape:", X.shape)
print("Mean of each feature:", X.mean(axis=0))

high_income = X[X[:, 1] > 800]

print("High income samples:")
print(high_income)

Shape: (5, 2)
Mean of each feature: [ 30. 900.]
High income samples:
[[  30  900]
 [  35 1100]
 [  40 1300]]
