# NumPy Foundations

## 1. Why do arrays exist?

In [1]:
import numpy as np

ages = np.array([19, 21, 20, 22, 18])

print(ages)
print(type(ages))


[19 21 20 22 18]
<class 'numpy.ndarray'>


In [2]:
print(ages + 1)
print(ages * 2)
print(ages - 5)
print(ages / 2)

[20 22 21 23 19]
[38 42 40 44 36]
[14 16 15 17 13]
[ 9.5 10.5 10.  11.   9. ]


Normal Python List 

In [3]:
ages_list = [19, 21, 20, 22, 18]

print(ages_list + [1])
print(ages_list * 2)

[19, 21, 20, 22, 18, 1]
[19, 21, 20, 22, 18, 19, 21, 20, 22, 18]


In [8]:
ages + 1


array([20, 22, 21, 23, 19])

In [5]:
ages + np.array([1, 1, 1, 1, 1])

array([20, 22, 21, 23, 19])

In [7]:
ages + np.array([1, 2, 3, 4, 5])

array([20, 23, 23, 26, 23])

What I understand now: NumPy arrays allow numerical operations to be applied element-by-element, unlike Python lists where + means concatenation.

In [9]:
print(ages.ndim)
print(ages.shape)

1
(5,)


In [11]:
marks = np.array([
    [80, 75, 90],
    [65, 88, 72],
    [92, 81, 95]
])
print(marks)
print(marks.ndim)
print(marks.shape)

[[80 75 90]
 [65 88 72]
 [92 81 95]]
2
(3, 3)


In [12]:
print(marks[0])
print(marks[1])
print(marks[2])

[80 75 90]
[65 88 72]
[92 81 95]


In [13]:
print(marks[0, 0])
print(marks[1, 2])
print(marks[2, 1])

80
72
81


In [14]:
marks[:, 0]

array([80, 65, 92])

In [15]:
marks[0, :]

array([80, 75, 90])

In [16]:

marks[:2, :]

array([[80, 75, 90],
       [65, 88, 72]])

In [17]:
marks[:, :2]

array([[80, 75],
       [65, 88],
       [92, 81]])

In [18]:
marks + 5

array([[ 85,  80,  95],
       [ 70,  93,  77],
       [ 97,  86, 100]])

In [19]:
marks * 2

array([[160, 150, 180],
       [130, 176, 144],
       [184, 162, 190]])

In [20]:
marks[:, 0] + 10

array([ 90,  75, 102])

In [21]:
print(marks)

[[80 75 90]
 [65 88 72]
 [92 81 95]]


In [22]:
marks_list = [
    [80, 75, 90],
    [65, 88, 72],
    [92, 81, 95]
]

# Normal Python approach
result = []

for row in marks_list:
    new_row = []
    for mark in row:
        new_row.append(mark + 5)
    result.append(new_row)

print(result)

[[85, 80, 95], [70, 93, 77], [97, 86, 100]]


In [23]:
print(marks + 5)

[[ 85  80  95]
 [ 70  93  77]
 [ 97  86 100]]


In [24]:
big_array = np.arange(1_000_000)

In [25]:
big_array + 10

array([     10,      11,      12, ..., 1000007, 1000008, 1000009],
      shape=(1000000,))